	[build]
	  command = "npm run build"
	  publish = "out"
	  functions = "netlify/functions"
	[[headers]]
	  for = "/*"
	  [headers.headers]
	    "X-Content-Type-Options" = "nosniff"
	    "X-Frame-Options" = "DENY"
	    "Content-Security-Policy" = "default-src 'self' 'unsafe-inline' 'unsafe-eval'"
	    "Referrer-Policy" = "strict-origin-when-cross-origin"
	[[redirects]]
	  from = "/api/*"
	  to = "/.netlify/functions/download/:splat"
	  status = 200